name: RaceDay CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check required folders and files
            - name: Check required folders and files
        run: |
          echo "Checking RaceDay repository structure..."
          test -d docs
          test -d .github/workflows
          test -f README.md
          test -f docs/API_Endpoint_Plan.md
          test -f docs/RaceDay_Database.sql
          test -f docs/RaceDay_ERD.png
          test -f .github/workflows/ci.yml
          echo "All required RaceDay files are present."
          echo "RaceDay repository structure is valid."
        